Set-Abbr sco "scoop"
Set-Abbr scl "scoop list"
Set-Abbr sclf "scoop list | rg"
Set-Abbr scb "scoop bucket"
Set-Abbr scc "scoop config"
Set-Abbr scin "scoop install"
Set-Abbr scun "scoop uninstall"
Set-Abbr scig "scoop install -g"
Set-Abbr scug "scoop uninstall -g"
Set-Abbr scs "scoop-search"
Set-Abbr scss "scoop status"
Set-Abbr scu "scoop update"
Set-Abbr scup "scoop update *"
