# =====================================================================
# Windots 配置与状态文件 (lib/config.ps1)
# =====================================================================

function Read-DataFile {
    param([Parameter(Mandatory)][string] $Path)
    if (-not (Test-Path $Path)) { throw (msg 'config.notfound' $Path) }
    return Import-PowerShellDataFile -Path $Path
}

function Resolve-RepoPath {
    param(
        [Parameter(Mandatory)][string] $RepoRoot,
        [Parameter(Mandatory)][string] $Value
    )
    if ([System.IO.Path]::IsPathRooted($Value)) { return $Value }
    return (Join-Path $RepoRoot $Value)
}

# packages.psd1 Dotfiles.Dest 占位符展开
# 支持：HOME\  APPDATA\  LOCAL_APPDATA\  HOMEPATH\  PROFILE  PROFILE_CurrentUserAllHosts
function Resolve-DestPath {
    param([Parameter(Mandatory)][string] $Dest)

    if ($Dest -eq 'PROFILE') { return $PROFILE }
    if ($Dest -eq 'PROFILE_CurrentUserAllHosts') { return $PROFILE.CurrentUserAllHosts }
    if ($Dest.StartsWith('HOME\')) { return Join-Path $HOME              $Dest.Substring(5) }
    if ($Dest.StartsWith('APPDATA\')) { return Join-Path $env:APPDATA       $Dest.Substring(8) }
    if ($Dest.StartsWith('LOCAL_APPDATA\')) { return Join-Path $env:LOCALAPPDATA  $Dest.Substring(13) }
    if ($Dest.StartsWith('HOMEPATH\')) { return Join-Path $env:HOMEPATH      $Dest.Substring(9) }
    return $Dest
}

function ConvertTo-PsLiteral {
    param([object] $Value)
    if ($null -eq $Value) { return '$null' }
    switch ($Value.GetType().FullName) {
        'System.Boolean' { return $(if ($Value) { '$true' } else { '$false' }) }
        'System.Int32' { return [string]$Value }
        'System.Int64' { return [string]$Value }
        'System.String' { return "'" + ($Value -replace "'", "''") + "'" }
    }
    if ($Value -is [System.Collections.IEnumerable] -and -not ($Value -is [hashtable])) {
        $items = @()
        foreach ($item in $Value) { $items += (ConvertTo-PsLiteral -Value $item) }
        return '@(' + ($items -join ', ') + ')'
    }
    if ($Value -is [hashtable]) {
        $parts = @()
        foreach ($k in $Value.Keys) { $parts += "$k = $(ConvertTo-PsLiteral -Value $Value[$k])" }
        return '@{ ' + ($parts -join '; ') + ' }'
    }
    return "'" + ($Value.ToString() -replace "'", "''") + "'"
}

function Save-WindotsState {
    param(
        [Parameter(Mandatory)][string]    $Path,
        [Parameter(Mandatory)][hashtable] $State
    )
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine('# Auto-generated by setup.ps1, do not edit by hand.')
    [void]$sb.AppendLine('@{')
    $sortedKeys = @($State.Keys | Sort-Object)
    $maxKeyLen = ($sortedKeys | ForEach-Object { $_.Length } | Measure-Object -Maximum).Maximum
    foreach ($key in $sortedKeys) {
        $pad = ' ' * ($maxKeyLen - $key.Length)
        [void]$sb.AppendLine("    $key$pad = $(ConvertTo-PsLiteral -Value $State[$key])")
    }
    [void]$sb.AppendLine('}')
    $utf8Bom = [Text.UTF8Encoding]::new($true)
    [IO.File]::WriteAllText($Path, $sb.ToString(), $utf8Bom)
}
