# =====================================================================
# Windots 配置与状态文件 (lib/config.ps1)
# =====================================================================

function Read-DataFile {
    param([Parameter(Mandatory)][string] $Path)
    if (-not (Test-Path $Path)) { throw (msg 'config.notfound' $Path) }
    return Import-PowerShellDataFile -Path $Path
}

function Resolve-RepoPath {
    param(
        [Parameter(Mandatory)][string] $RepoRoot,
        [Parameter(Mandatory)][string] $Value
    )
    if ([System.IO.Path]::IsPathRooted($Value)) { return $Value }
    return (Join-Path $RepoRoot $Value)
}

# packages.psd1 Dotfiles.Dest 占位符展开
# 支持：HOME\  APPDATA\  LOCAL_APPDATA\  HOMEPATH\  PROFILE  PROFILE_CurrentUserAllHosts
function Resolve-DestPath {
    param([Parameter(Mandatory)][string] $Dest)

    if ($Dest -eq 'PROFILE') { return $PROFILE }
    if ($Dest -eq 'PROFILE_CurrentUserAllHosts') { return $PROFILE.CurrentUserAllHosts }
    if ($Dest.StartsWith('HOME\')) { return Join-Path $HOME              $Dest.Substring(5) }
    if ($Dest.StartsWith('APPDATA\')) { return Join-Path $env:APPDATA       $Dest.Substring(8) }
    if ($Dest.StartsWith('LOCAL_APPDATA\')) { return Join-Path $env:LOCALAPPDATA  $Dest.Substring(13) }
    if ($Dest.StartsWith('HOMEPATH\')) { return Join-Path $env:HOMEPATH      $Dest.Substring(9) }
    return $Dest
}

# packages.psd1 Desc 字段解析
# 字符串 Desc：任意语言通用
# 对象 Desc：当前语言 Desc > i18n 当前语言 > 默认语言 Desc > i18n 默认语言
# 无 Desc：i18n 当前语言 > i18n 默认语言
function Get-PackageI18nDesc {
    param(
        [Parameter(Mandatory)][string] $Name,
        [ValidateSet('Any', 'Primary', 'Fallback')]
        [string] $Scope = 'Any'
    )

    $descKey = "pkg.$Name.desc"
    if ($Scope -in 'Any', 'Primary') {
        if ($null -ne $Global:WindotsMessages -and $Global:WindotsMessages.ContainsKey($descKey)) {
            return [string]$Global:WindotsMessages[$descKey]
        }
    }
    if ($Scope -in 'Any', 'Fallback') {
        if ($null -ne $Global:WindotsMessagesFallback -and $Global:WindotsMessagesFallback.ContainsKey($descKey)) {
            return [string]$Global:WindotsMessagesFallback[$descKey]
        }
    }
    return ''
}

function Get-PackageDesc {
    param(
        [Parameter(Mandatory)]
        $Package
    )

    $name = [string]$Package.Name
    if ([string]::IsNullOrWhiteSpace($name)) { return '' }

    $locale = [string]$Global:WindotsLocale
    $defaultLocale = $Script:WindotsDefaultLocale

    if ($Package.Contains('Desc') -and $null -ne $Package.Desc) {
        $desc = $Package.Desc
        if ($desc -is [string]) {
            $text = $desc.Trim()
            if ($text) { return $text }
        }
        elseif ($desc -is [System.Collections.IDictionary]) {
            if ($desc.Contains($locale)) {
                $text = [string]$desc[$locale]
                if (-not [string]::IsNullOrWhiteSpace($text)) { return $text.Trim() }
            }

            $primaryI18n = Get-PackageI18nDesc -Name $name -Scope Primary
            if ($primaryI18n) { return $primaryI18n }

            if ($locale -ne $defaultLocale -and $desc.Contains($defaultLocale)) {
                $text = [string]$desc[$defaultLocale]
                if (-not [string]::IsNullOrWhiteSpace($text)) { return $text.Trim() }
            }

            $fallbackI18n = Get-PackageI18nDesc -Name $name -Scope Fallback
            if ($fallbackI18n) { return $fallbackI18n }

            return ''
        }
    }

    $i18nDesc = Get-PackageI18nDesc -Name $name
    if ($i18nDesc) { return $i18nDesc }
    return ''
}

function ConvertTo-PsLiteral {
    param([object] $Value)
    if ($null -eq $Value) { return '$null' }
    switch ($Value.GetType().FullName) {
        'System.Boolean' { return $(if ($Value) { '$true' } else { '$false' }) }
        'System.Int32' { return [string]$Value }
        'System.Int64' { return [string]$Value }
        'System.String' { return "'" + ($Value -replace "'", "''") + "'" }
    }
    if ($Value -is [System.Collections.IEnumerable] -and -not ($Value -is [hashtable])) {
        $items = @()
        foreach ($item in $Value) { $items += (ConvertTo-PsLiteral -Value $item) }
        return '@(' + ($items -join ', ') + ')'
    }
    if ($Value -is [hashtable]) {
        $parts = @()
        foreach ($k in $Value.Keys) { $parts += "$k = $(ConvertTo-PsLiteral -Value $Value[$k])" }
        return '@{ ' + ($parts -join '; ') + ' }'
    }
    return "'" + ($Value.ToString() -replace "'", "''") + "'"
}

function Save-WindotsState {
    param(
        [Parameter(Mandatory)][string]    $Path,
        [Parameter(Mandatory)][hashtable] $State
    )
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine('# Auto-generated by setup.ps1, do not edit by hand.')
    [void]$sb.AppendLine('@{')
    $sortedKeys = @($State.Keys | Sort-Object)
    $maxKeyLen = ($sortedKeys | ForEach-Object { $_.Length } | Measure-Object -Maximum).Maximum
    foreach ($key in $sortedKeys) {
        $pad = ' ' * ($maxKeyLen - $key.Length)
        [void]$sb.AppendLine("    $key$pad = $(ConvertTo-PsLiteral -Value $State[$key])")
    }
    [void]$sb.AppendLine('}')
    $utf8Bom = [Text.UTF8Encoding]::new($true)
    [IO.File]::WriteAllText($Path, $sb.ToString(), $utf8Bom)
}
